# 딥러닝 개좆밥이 조금이라도 더 이해해보자고 쓰는 Pytorch 튜토리얼 1
워낙에 아는게 없기 때문에 쓸데없어 보이는 별의별거 다 들어가는 튜토리얼

### Pytorch는 무엇인가?
pyTorch 공식 튜토리얼 https://pytorch.org/tutorials/ 에서는, PyTorch에 대해 다음과 같이 설명하고 있다.

PyTorch는 파이썬 기반의 과학 컴퓨팅 패키지로 두 집단을 대상으로 합니다.
   * NumPy를 대체하고 GPU의 힘을 사용
   * 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플래폼
   
...라고 설명되어 있다. 그러나 이 설명만으로는 기존에 Torch를 사용해보지 않았거나 딥러닝을 이제 막 공부하기 시작한 사람들에게는<br>
충분하지 않은 설명이라고 생각되어 추가적으로 Torch에 대해 설명해보자면,

## Torch
Torch는 GPU를 사용하면서 객체지향적으로 모델을 만드는 Lua를 사용하는 딥러닝 라이브러리이다.<br>
Torch는 다음과 같은 특징을 갖고 있다.
   * Python보다 빠름. Just in time compilation(JIT 컴파일, 동적번역으로 프로그램을 실행하는 시점에 기계어로 번역하는 것) 때문에.
   * Luarocks로 Python의 pip처럼 lua package를 설치   
   * 페이스북, 딥마인드, 트위터 등 여러회사에서 사용
   * Numpy처럼 다룰 수 있음
   * 모듈안에 자신의 코드를 만들어서 사용가능
   * 네트워크 구조를 짜는 것이 아닌, 텐서와 텐서를 연결하는 node를 만들어서 구현
   
과 같은 특징을 갖고 있다. 다음과 같은 특징들에서 나오는 Torch의 장점으로는 
   * 결합시키기 쉬운 많은 모듈러 조각을 만들 수 있음
   * 다른 딥러닝 라이브러리와 비교해서 GPU를 이용한 코딩이 매우 쉬움
   * 대부분의 참조하는 라이브러리 코드가 Lua에 있으며, 읽기가 쉬움
   * 많은 사전 훈련된 모델
   
과 같은 장점들이 있다. 반면 단점으로는 다음과 같은 단점들이 있는데,
   * **Lua**
   * Caffe보다 플러그 앤 플레이가 적음
   * RNN에는 적합하지 않음
   
이 있다. Torch는 이전부터 좋은 딥러닝 라이브러리로 평가 받았지만 Lua를 사용한다는 것이 문제가 되었다. <br>
물론 Lua를 배워서라도 하려는 사람들이 많을 정도로 좋은 라이브러리지만, 강조했듯이 **Lua**의 진입장벽이 가장 큰 단점으로 작용했고,<br>
이 Torch 라이브러리를 Python으로 컨버팅하여 만든것이 바로 PyTorch다.<br>
여기에 Pytorch는 Python으로 컨버팅을 하게 되면서 Python의 다른 계산 모듈들을 사용할 수 있게 되는 더욱 큰 장점을 가지게 되었다.
~~http://tmmse.xyz/2016/02/25/choosing-deep-learning-libraries/ 참조~~

### PyTorch와 Tensorflow의 차이
딥러닝 공부를 시작하면서 많은 사람들이 Pytorch와 Tensorflow 둘 중 에서 무엇으로 시작할지 고민을 하고 있고, 가장 많이 사용되는 두가지 딥러닝 라이브러리의 차이를 알기 위해 두 라이브러리의 차이점을 찾아보게 되었다.<br>

가장 큰 차이점으로는 Tensorflow는 static하고, Pytorch는 dynamic하다는 것이다.<br>
Tensorflow의 경우에는 그래프 구조를 먼저 그려놓고, 그것을 fix해서 데이터가 그 안에서 흐르게 되는 구조로 간단히 요약하면<br>
모델을 설정하고 데이터를 돌리는 2가지의 단계로 명확히 구분지어져 있다.<br>
해당 구조의 단점은 런타임에서 사용자가 인터렉티브하게 개입하거나 중간에 구조가 바뀌던가 하는 조정이 불가능하다는 것이다.<br><br>

반면에 Pytorch의 경우에는 Tensorflow보다 훨씬 늦게 나왔는데, (Torch를 기준으로 1년정도, Pytorch의 경우 2년 정도)<br>
나중에 나온 라이브러리인 만큼 Tensorflow의 단점을 수정하고 나오게 되면서 Tensorflow의 단점인 static한 구조를 수정해서 나오게 되었다.<br>

또 다른 차이점으로는 Pytorch는 기존에 우리가 하듯이 runtime debugging을 할 수 있지만, Tensorflow는 실행중 중간에 개입하여 디버깅하기가<br>굉장히 힘들다. (tfdbg라는 툴을 이용하면 가능하지만, 처음부터 지원이 되는것과는 비교하기 힘들다.)<br>

Tensorflow의 장점으로는 visuallization, 시각화가 있다. Tensorflow의 TensorBoard는 시각화쪽에서 굉장히 강력한 성능을 제공하고 있다.<br>
반면에 Pytorch는 공식적인 시각화 툴이 없다. (Visdom이라는 툴이 최근에 제공되기 시작함)<br>

또한 Tensorflow의 사용자 커뮤니티가 Pytorch의 사용자 커뮤니티보다 훨씬 크다는 것도 Tensorflow의 큰 장점이다.<br>
~~당장 facebook 그룹의 인원부터 Tensorflow KR의 사용자수는 약 4만명인데 비해, Pytorch KR의 사용자는 약 5500명으로 큰차이가 난다.~~<br>
그만큼 Tensorflow쪽이 코드를 찾거나, 질문과 답을 찾거나 정보를 구하기가 Pytorch에 비해 훨씬 쉬우며 이로인해 Tensorflow가<br>
Pytorch보다 쉽게 느껴지게 된다.<br>
~~물론 Pytorch도 기본적인 정보와 커뮤니티는 존재하지만, Tensorflow의 커뮤니티보다 적은건 사실이다.~~<br>

Low, High-Level적인 측면에서는 Tensorflow는 점점 라이브러리가 커지면서 거의 C 수준으로 low-Level까지 컨트롤 할 수 있게 컨트롤 할 수 있도록
라이브러리가 많이 커졌다.<br>
반면 PyTorch는 딥러닝 자체의 구조만을 만들고 실행시키는 것에 관련해서만 집중되어 있다.<br>
이로인해 요소, 변수가 많은 실제 업무에서 쓰일 용도로는 Tensorflow가 조금 더 좋고, 공부 또는 개인적인 용도로 사용하는데는 PyTorch가 조금 더 좋다.<br>

~~위에 차이점 표 첨부해야될듯~~
~~http://bitly.kr/9YDB http://bitly.kr/9YDB 참조~~<br>

## Pytorch 시작하기

### Tensors

#### Tensor는 무엇인가
Tensor는 수학과 과학에서 선형 관계를 나타내는 기하적 대상이다. 텐서에 대하여 쉽게 설명을 해보자면,<br>
<br>
A가 자신의 집으로 가는 방법을 표현한다고 할 경우, A가 "내 집은 여기서 3km 떨어져 있어"에서 3km는 스칼라가 되고,<br>
"내 집으로 가려면 여기서 2km를 북쪽으로 간 후 1km 동쪽으로가서 3계단 올라가야 해."라는 답으로 3개의 공간 성분을 가진 3차원 벡터가 만들어지는<br> 것을 확인 할 수가 있다.<br>

여기서 벡터에 스칼라를 곱하는 경우 v = au 와 같은식으로 쉽게 곱할 수 있다.<br>
그런데 방향과 크기를 동시에 바꾸려면 단순히 스칼라를 곱해서는 안된다. 다른 벡터와의 외적 역시 곱하면 무조건 직각으로만 바뀌기 때문에 안된다.<br>
따라서 **한번에 방향과 크기를 동시에 바꿔줄 것**이 필요하게 되고, 이를 위해 백터를 복합적으로 연결시킨 구조를 **Tensor**라고 한다.

#### Pytorch에서의 Tensor 선언
    Pytorch의 Tensor는 NumPy의 ndarray와 유사할뿐만 아니라, GPU를 사용한 연산 가속도 지원한다.

In [1]:
from __future__ import print_function
import torch

In [2]:
# 초기화 되지 않은 5x3 행렬을 생성한다.
x = torch.Tensor(5, 3)
print(x)

tensor(1.00000e-19 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  1.6109,  0.0000]])


In [3]:
# 무작위로 초기화된 5x3 행렬을 생성한다.
x = torch.rand(5, 3)
print(x)

tensor([[ 0.7750,  0.1933,  0.3376],
        [ 0.6186,  0.0879,  0.2701],
        [ 0.8082,  0.4008,  0.5986],
        [ 0.8133,  0.8259,  0.9688],
        [ 0.5040,  0.7888,  0.9928]])


In [4]:
# 행렬의 크기를 구한다.
print(x.size())

torch.Size([5, 3])


### Tensor의 연산
    PyTorch는 연산을 위한 여러가지 문법을 제공한다.

In [11]:
y = torch.rand(5, 3)
# 여러 덧셈 문법
print (x)
print (y)
print(x + y)

tensor([[ 0.7750,  0.1933,  0.3376],
        [ 0.6186,  0.0879,  0.2701],
        [ 0.8082,  0.4008,  0.5986],
        [ 0.8133,  0.8259,  0.9688],
        [ 0.5040,  0.7888,  0.9928]])
tensor([[ 0.5452,  0.6278,  0.0987],
        [ 0.1394,  0.8774,  0.7473],
        [ 0.8053,  0.4184,  0.9333],
        [ 0.9985,  0.8164,  0.2633],
        [ 0.6394,  0.1485,  0.8014]])
tensor([[ 1.3202,  0.8211,  0.4363],
        [ 0.7580,  0.9653,  1.0174],
        [ 1.6134,  0.8192,  1.5319],
        [ 1.8118,  1.6423,  1.2321],
        [ 1.1434,  0.9373,  1.7941]])


In [7]:
print(torch.add(x, y))

tensor([[ 1.2589,  0.6229,  0.9439],
        [ 1.3883,  0.2435,  0.7242],
        [ 1.4421,  0.9395,  1.4655],
        [ 0.9990,  1.6243,  1.9219],
        [ 1.4742,  1.0063,  1.1258]])


In [8]:
# 덧셈 결과를 텐서 인자로 제공
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.2589,  0.6229,  0.9439],
        [ 1.3883,  0.2435,  0.7242],
        [ 1.4421,  0.9395,  1.4655],
        [ 0.9990,  1.6243,  1.9219],
        [ 1.4742,  1.0063,  1.1258]])


In [9]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[ 1.2589,  0.6229,  0.9439],
        [ 1.3883,  0.2435,  0.7242],
        [ 1.4421,  0.9395,  1.4655],
        [ 0.9990,  1.6243,  1.9219],
        [ 1.4742,  1.0063,  1.1258]])


In [10]:
# Numpy의 인덱싱 표기방법을 사용 할 수도 있음
print(x[:, 1])

tensor([ 0.1933,  0.0879,  0.4008,  0.8259,  0.7888])


In [13]:
# 텐서의 크기(size)나 모양(shape)을 변경하고 싶을 때, torch.view 를 사용한다.
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # 사이즈가 -1인 경우 다른 차원들을 사용하여 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### NumPy 변환(Bridge)
    Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 변하게 하는 것은 매우 쉽다.
    Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.

In [18]:
# Torch Tensor 선언
a = torch.ones(5)
print(a)
print("\n")
# Numpy array 선언
b = a.numpy()
print(b)
print("\n")

# Numpy array와 Torch Tensor사이의 연산
a.add_(1)
print(a)
print(b)
print("\n") # 한쪽에만 더해주었는데 같이 변하는 걸 확인 - 저장공간을 공유함

tensor([ 1.,  1.,  1.,  1.,  1.])


[1. 1. 1. 1. 1.]


tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]




In [19]:
# 반대로 np배열의 값을 변화시켜도 torch tensor의 값도 변한다.
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


### CUDA Tensors
    .to 메소드를 사용하여 Tensor를 GPU 상으로 옮길 수 있다.    

In [24]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행 가능하다.
# ``torch.device`` 를 사용하여 tensor를 GPU로 이동하는 예제
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(Device Object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 바로(directly) tensor를 생성하거나
    x = x.to(device)                       # 단지 ``.to("cuda")`` 라고만 작성하면 됨
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경함

tensor([[ 0.6398,  2.4916,  0.8794,  0.2813],
        [ 0.5152,  1.0626, -0.8613, -1.9972],
        [-0.1854,  4.2127,  1.3663,  0.9738],
        [ 0.4678,  0.6055,  0.6897,  0.0511]], device='cuda:0')
tensor([[ 0.6398,  2.4916,  0.8794,  0.2813],
        [ 0.5152,  1.0626, -0.8613, -1.9972],
        [-0.1854,  4.2127,  1.3663,  0.9738],
        [ 0.4678,  0.6055,  0.6897,  0.0511]], dtype=torch.float64)


## 신경망
신경망이란

## Pytorch에서의 신경망
신경망은 torch.nn 패키지를 사용하여 생성할 수 있습니다.

지금까지 autograd 를 살펴봤는데요, nn 은 모델을 정의하고 미분하는데 autograd 를 사용합니다.<br>
nn.Module 은 계층(layer)과 output 을 반환하는 forward(input) 메서드를 포함하고 있습니다.<br>
숫자 이미지를 분류하는 신경망을 예제로 살펴보겠습니다<br>
이는 간단한 피드-포워드 네트워크(Feed-forward network)이다. 입력(input)을 받아 여러 계층에 차례로 전달한 후,<br>
최종 출력(output)을 제공하게 된다.

신경망의 학습 과정은 대체로 다음과 같다.
   * 학습 가능한 매개변수(또는 가중치(weight))를 갖는 신경망을 정의합니다.
   * 데이터셋(dataset) 입력을 반복합니다.
   * 입력을 신경망에서 처리합니다.
   * 손실(loss; 출력이 정답으로부터 얼마나 떨어져있는지)을 계산합니다.
   * 변화도(gradient)를 신경망의 매개변수들에 역으로 전파합니다.
   * 신경망의 가중치를 갱신합니다. 일반적으로 다음과 같은 간단한 규칙을 사용합니다:

### Pytorch에서 신경망 정의하기

In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


forward 함수만 정의하고 나면, (변화도를 계산하는)backward 함수는 autograd 를 사용하여 자동으로 정의된다.<br>
forward 함수에서는 어떠한 Tensor 연산을 사용해도 된다.<br>

모델의 학습 가능한 매개변수들은 net.parameters()에 의해 반환된다.<br>

In [26]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([6, 1, 5, 5])


임의의 32x32 입력값을 넣어보겠습니다. 이 신경망에 MNIST 데이터셋을 사용하기 위해서는, 데이터셋의 이미지를 32x32로 크기를 변경해야 한다.

In [27]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0439, -0.0381,  0.1588,  0.0189,  0.0476, -0.1660,  0.0868,
         -0.1205,  0.2261, -0.1901]])


모든 매개변수의 변화도 버퍼(gradient buffer)를 0으로 설정하고, 무작위 값으로 역전파를 한다.

In [28]:
net.zero_grad()
out.backward(torch.randn(1, 10))

    torch.nn 은 미니 배치(mini-batch)만 지원합니다. torch.nn 패키지 전체는 하나의 샘플이 아닌, 샘플들의 미니배치만을 입력으로 받습니다.
    예를 들어, nnConv2D 는 nSamples x nChannels x Height x Width 의 4차원 Tensor를 입력으로 합니다.
    만약 하나의 샘플만 있다면, input.unsqueeze(0) 을 사용해서 가짜 차원을 추가합니다.
    
    미니 배치란

### 손실 함수 (Loss Function)

손실 함수란?



손실 함수는 (output, target)을 한 쌍(pair)의 입력으로 받아, 출력(output)이 정답(target)으로부터 얼마나<br>
떨어져있는지를 추정하는 값을 계산합니다.

nn 패키지에는 여러가지의 손실 함수들 이 존재한다. 간단한 손실 함수로는 출력과 대상간의 평균자승오차(mean-squared error)를<br>
계산하는 nn.MSEloss 가 있다.

In [29]:
output = net(input)
target = torch.arange(1, 11)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(38.6089)


.grad_fn 속성을 사용하여 loss 를 역방향에서 따라가다보면, 다음과 같은 모습의 연산 그래프를 볼 수 있다.

    input -> conv2d -> relu -> maxpool2d -> conv2d -> relu -> maxpool2d<br>
          -> view -> linear -> relu -> linear -> relu -> linear<br>
          -> MSELoss<br>
          -> loss<br>
      
따라서, loss.backward() 를 실행할 때, 전체 그래프는 손실(loss)에 대해 미분되며, 그래프 내의 requires_grad=True 인 모든 Tensor는<br>
변화도(Gradient)가 누적된 .grad Tensor를 갖게 된다.<br>

In [32]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

### 역전파

역전파란?

오차(error)를 역전파하기 위해 할 일은 loss.backward() 이 전부다. 이 때 기존 변화도를 지우는 작업이 필요한데,<br>
그렇지 않으면 변화도가 기존의 것에 누적된다.<br>

이제 loss.backward() 를 호출하여 역전파 전과 후에 conv1의 bias gradient를 살펴보면,<br>


In [33]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([ 0.,  0.,  0.,  0.,  0.,  0.])
conv1.bias.grad after backward
tensor([ 0.0974, -0.0964,  0.0174, -0.0673,  0.1015,  0.0734])


### 가중치
가중치란?
    
실제로 많이 사용되는 가장 단순한 갱신 규칙은 확률적 경사하강법(SGD; Stochastic Gradient Descent)입니다:

    가중치(wiehgt) = 가중치(weight) - 학습율(learning rate) * 변화도(gradient)    
간단한 Python 코드로 이를 구현해볼 수 있다.

In [34]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

그러나, 신경망을 구성할 때 SGD, Nesterov-SGD, Adam, RMSProp 등과 같은 다양한 갱신 규칙을 사용하고 싶을 수 있다.<br>
이를 위해서 torch.optim 라는 작은 패키지에 이러한 방법들을 모두 구현되어 있다.<br>

In [35]:
import torch.optim as optim

# Optimizer를 생성합니다.
optimizer = optim.SGD(net.parameters(), lr=0.01)

# 학습 과정(training loop)에서는 다음과 같습니다:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update

optimizer.zero_grad() 를 사용하여 수동으로 변화도 버퍼를 0으로 설정하는 것에 유의하세요. 이는 역전파(Backprop) 섹션에서 설명한 것처럼 변화도가 누적되기 때문입니다.